USE QLBH
---1a
CREATE VIEW DANHSACHDETAI_REPORT
AS
SELECT DETAI.MSDT, TENDT, GIAOVIEN.MSGV, TENGV FROM DETAI JOIN GV_HDDT ON DETAI.MSDT = GV_HDDT.MSDT
JOIN GIAOVIEN ON GIAOVIEN.MSGV = GV_HDDT.MSGV

SELECT * FROM DANHSACHDETAI_REPORT
---1b
CREATE VIEW HD_DT
AS SELECT HOIDONG.MSHD, PHONG, TENDT, DETAI.MSDT, QUYETDINH
FROM HOIDONG, HOIDONG_DT, DETAI
WHERE HOIDONG.MSHD=HOIDONG_DT.MSHD
AND HOIDONG_DT.MSDT=DETAI.MSDT

SELECT * FROM HD_DT

---1c
CREATE TABLE DETAI_DIEM
(
	MSDT CHAR(6) PRIMARY KEY,
	DIEMTB FLOAT
)
drop table DETAI_DIEM
--Cursor
DECLARE @DUYET CURSOR, @MSDT CHAR(6), @DTB FLOAT;
SET @DUYET = CURSOR FOR SELECT MSDT FROM DETAI
OPEN @DUYET
FETCH NEXT FROM @DUYET INTO @MSDT
WHILE @@FETCH_STATUS = 0 
BEGIN 
	SET @DTB = DBO.TINHDTB(@MSDT)
	INSERT INTO DETAI_DIEM VALUES (@MSDT, @DTB)
	FETCH NEXT FROM @DUYET INTO @MSDT
END
CLOSE @DUYET
DEALLOCATE @DUYET

SELECT * FROM DETAI_DIEM
--view
CREATE VIEW DETAI_DTB_view AS
WITH HOIDONG_DT_RANKED AS (
    SELECT MSDT, MSHD, QUYETDINH,
           ROW_NUMBER() OVER (PARTITION BY MSDT ORDER BY MSHD) AS rn
    FROM HOIDONG_DT
)
SELECT DISTINCT DETAI.MSDT, DETAI.TENDT, HOIDONG_DT_RANKED.MSHD, DETAI_DIEM.DIEMTB
FROM DETAI
INNER JOIN DETAI_DIEM ON DETAI.MSDT = DETAI_DIEM.MSDT
INNER JOIN HOIDONG_DT_RANKED ON DETAI.MSDT = HOIDONG_DT_RANKED.MSDT
WHERE HOIDONG_DT_RANKED.rn = 1;
SELECT *  from DETAI_DTB_view

---1d
CREATE VIEW DoanhSoNhanVien2006 AS
SELECT 
    NHANVIEN.MANV + '-' + NHANVIEN.HOTEN AS MaNV_HoTen,
    MONTH(HOADON.NGHD) AS Thang,
    SUM(HOADON.TRIGIA) AS DoanhSo
FROM 
    HOADON
JOIN 
    NHANVIEN ON HOADON.MANV = NHANVIEN.MANV
WHERE 
    YEAR(HOADON.NGHD) = 2006
GROUP BY 
    NHANVIEN.MANV, NHANVIEN.HOTEN, MONTH(HOADON.NGHD);

	Select * from DoanhSoNhanVien2006